export const FILTER_MODE_ALL = 'FILTER_MODE_ALL';
export const FILTER_MODE_LIKE = 'FILTER_MODE_LIKE';
export const FILTER_MODE_DISLIKE = 'FILTER_MODE_DISLIKE';
export const FILTER_MODE_ALPHABET = 'FILTER_MODE_ALPHABET';
export const FILTER_MODE_RESET = 'FILTER_MODE_RESET';
